services:
  users:
    read_only: false
    build:
      context: ./services/users
      target: development
    volumes:
      - ./services/users:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://admin:password123@user-db:5432/user_db
      - SERVICE_NAME=users-service
      - NODE_OPTIONS=--require ./tracing.js
  orders:
    read_only: false
    build:
      context: ./services/orders
      target: development
    volumes:
      - ./services/orders:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://order-db:27017/orders
      - SERVICE_NAME=orders-service
      - NODE_OPTIONS=--require ./tracing.js

  gateway:
    ports:
      - "8080:80"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
