services:
  users:
    build:
      context: ./services/users
      target: development
    volumes:
      - ./services/users:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://admin:password123@user-db:5432/user_db
  orders:
    build:
      context: ./services/orders
      target: development
    volumes:
      - ./services/orders:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://order-db:27017/orders
