global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets: ['users:3000','orders:3000']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rmq:15692']
  - job_name: 'cadvisor'
    static_configs:
      -  targets: ['cadvisor:8080']
